### ISSUE TITLE
Hook False

### ISSUE THREAD

**Issue by Retimeup** [Z4kSec/IoctlHunter#1]
![image](https://github.com/Z4kSec/IoctlHunter/assets/85960806/3b0b7196-b605-4863-a170-918ffc32c32c)

**Comment by Z4kSec** [comment]
Hi @Retimeup ,

Thanks for testing IoctlHunter!

The tool works by using dynamic keyboard events to enable/disable features while conducting an analysis.

You can activate or deactivate the hooking mode by pressing `[SPACE]`. Please note that all key events can be listed by pressing `[H]`.

Alternatively, the hooking mode can be enabled at the start by running IoctlHunter with the `-hos` (`--hook-on-start`) parameter.
